### ISSUE TITLE
这周的学习总结也抓紧提交吧

### ISSUE THREAD

**Issue by nimoc** [2319103827/lean#1]

**Comment by 2319103827** [comment]
## 好的

现在慢慢能体会你之前说的那种感觉，就是说随便在哪里都能高效率的编程，现在我还达不到你那么高的境界啦……，不过体会可能有两点：
- 团队氛围
- 习惯 

还有你境界太高了，你还是多休息吧，看你这些天是没休息好吧，晚上运动量太大了哦，有时间聚餐…………
